# Generated by Django 2.2.2 on 2019-07-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(help_text=' unique value for product url created frome name ', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(help_text='for meta tags ', max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(help_text='for meta tags ', max_length=255, verbose_name='Meta Description ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(help_text='Unique product page url , created from Name ', max_length=255, unique=True)),
                ('descreption', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('pubdate', models.DateTimeField(auto_now=True)),
                ('img', models.CharField(max_length=50, null=True)),
                ('meta_description', models.CharField(help_text='.....', max_length=255, null=True)),
                ('meta_keywords', models.CharField(help_text='.....', max_length=255, null=True)),
                ('ctgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catloge.Categorie')),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_to', models.CharField(max_length=100)),
                ('orderdate', models.DateTimeField(auto_now=True)),
                ('clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catloge.Client')),
                ('itm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catloge.Item')),
            ],
            options={
                'ordering': ['-orderdate'],
            },
        ),
    ]
