# Generated by Django 2.2.2 on 2019-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloge', '0002_auto_20190701_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, help_text=' unique value for product url created frome name '),
        ),
    ]
