# Generated by Django 2.2.3 on 2019-07-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloge', '0007_auto_20190705_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_img_1',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='img/product/'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_img_2',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='img/product/'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_img_3',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='img/product/'),
        ),
    ]
